kind = "web"
previewPath = "/"
title = "Enigma-OF-Alchemist"
version = "1.0.0"
id = "artifacts/3d-game"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24982

[services.development]
run = "pnpm --filter @workspace/3d-game run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/3d-game", "run", "build" ]
publicDir = "artifacts/3d-game/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24982"
BASE_PATH = "/"
